### ISSUE TITLE
Publish binary artifacts via Github releases

### ISSUE THREAD

**Issue by emmanuel** [Nordstrom/kubelogin#17]
`kubelogin` has a binary artifact for users to download: the CLI binary. We should distribute this via the Github releases feature.

**Comment by adamcarlton** [comment]
wouldn't this sorta defeat the purpose of the download page?

**Comment by emmanuel** [comment]
Largely, yes. The download page will provide a way to download a version of the CLI that matches the version of the server. But in general the GitHub releases would replace usage of the download page. 

If someone had thought of it sooner, we could have started with GH Releases and skipped the download page (at least the download part, I think the built-in docs are still valuable); indsight is 20:20.

**Comment by adamcarlton** [comment]
Fair enough. I was unaware Github had a feature like that. Ah well. Now there are 2 ways for people to download the CLI
