### ISSUE TITLE
When the container is built the client downloads fail

### ISSUE THREAD

**Issue by SleepyBrett** [Nordstrom/kubelogin#27]
All the downloads are nine bytes 'Not Found'.

The download urls are slightly wrong, should be Tag-Platform not Platform-Tag

**Comment by adamcarlton** [comment]
Could you be a little more specific as to the problem? IIRC this wasn't an issue while I was there

**Comment by adamcarlton** [comment]
Actually I know it wasn't an issue. What changed 🤔

**Comment by SleepyBrett** [comment]
i found it, watch for the pull request

**Comment by SleepyBrett** [comment]
https://github.com/Nordstrom/kubelogin/pull/28

**Comment by adamcarlton** [comment]
👌🏼 Hope my app has been useful

**Comment by emmanuel** [comment]
Fixed by #28
