### ISSUE TITLE
Large tokens truncated due to Shell command

### ISSUE THREAD

**Issue by tylerdavisnordstrom** [Nordstrom/kubelogin#41]
Writing the JWT token to the appropriate kubectl config is accomplished by executing a shell command with the token passed on the command line [as detailed on cmd/cli/main.go#L113](https://github.com/Nordstrom/kubelogin/blob/master/cmd/cli/main.go#L113).

Due to [limitations in the length of command line arguments on windows](https://support.microsoft.com/en-us/help/830473/command-prompt-cmd--exe-command-line-string-limitation), any token which exceeds 8191 characters will be truncated.  

To resolve this, we need to parse and write the `~/.kube/config` YAML file directly.

**Comment by mariusgrigoriu** [comment]
Encountered a few more people affected by this one.
