### ISSUE TITLE
Refactor package layout

### ISSUE THREAD

**Issue by emmanuel** [Nordstrom/kubelogin#8]
@adamcarlton move `kubelogin_server.go` to `cmd/server/main.go` and move any supporting packages to `pkg/SOMETHING`. The `pkg/*` tree is for things shared by the server and client, or things that are used in the server, but not directly part of its `main`.

See https://github.com/coreos/dex/tree/master/cmd/example-app for an example.

**Comment by adamcarlton** [comment]
Fixed 👍
